name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: true
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      USE_SSH: true
      GIT_USER: petyosi
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    steps:
      - name: Begin CI...
        uses: actions/checkout@v4

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: | 
          npm install
          npm install --workspaces

      - name: run CI checks
        run: |
          npm run ci

      - name: Release
        id: changesets
        if: github.ref == 'refs/heads/master'
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-react-virtuoso
          path: packages/react-virtuoso/playwright-report/
          retention-days: 7
